insert into famille (id, libelle) values (1, 'Wilkinson and Sons');
insert into famille (id, libelle) values (2, 'Gleason-Hills');
insert into famille (id, libelle) values (3, 'Wolf-Roberts');
insert into famille (id, libelle) values (4, 'Mills and Sons');
insert into famille (id, libelle) values (5, 'Carroll Group');
insert into famille (id, libelle) values (6, 'Dicki and Sons');
insert into famille (id, libelle) values (7, 'Crooks Inc');
insert into famille (id, libelle) values (8, 'Schneider, Robel and Stanton');
insert into famille (id, libelle) values (9, 'Langosh, Jones and Crona');
insert into famille (id, libelle) values (10, 'Corwin, Larson and Koepp');
insert into famille (id, libelle) values (11, 'Kilback-Boyle');
insert into famille (id, libelle) values (12, 'Harber LLC');
insert into famille (id, libelle) values (13, 'Huel, Bashirian and Schuster');
insert into famille (id, libelle) values (14, 'Zboncak-Davis');
insert into famille (id, libelle) values (15, 'Kovacek-Wolff');
insert into famille (id, libelle) values (16, 'West LLC');
insert into famille (id, libelle) values (17, 'Weissnat-Harber');
insert into famille (id, libelle) values (18, 'Wolf-Conroy');
insert into famille (id, libelle) values (19, 'Hamill-Volkman');
insert into famille (id, libelle) values (20, 'Brown-Cummerata');
